### ISSUE TITLE
[WASAPI] ERole == `eMultimedia` should not be used

### ISSUE THREAD

**Issue by padenot** [kinetiknz/cubeb#105]
While re-reading some [WASAPI docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd756517(v=vs.85).aspx), I found this:

> The client must also specify the appropriate role for the endpoint in the
> ERole attribute (eConsole or eCommunications). Do not use eMultimedia.

We're using `eMultimedia`, and we've never had issues, but maybe we could reconsider.

**Comment by kinetiknz** [comment]
Yeah, I've run into this several times before when debugging and wondering if some weird behaviour was related to that (but never was).  AFAIK there's no reason we are using eMultimedia, so let's change it.

**Comment by kinetiknz** [comment]
Fixed in 05abb60b99a46d1d21abe58d9e5f3bdb4f0df4a8.
