### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by andrewrk** [kinetiknz/cubeb#122]
Hi there, libsoundio developer here. I'm just curious about your project. It looks cool. What are some of the goals?

I'm looking forward to collaborating and cross-referencing each other's code in order to solve bugs.

**Comment by padenot** [comment]
This repo contains the audio input and output code for the Firefox web browser. It's a separate library so it's easier to work on.

It's supposed to support all the platforms that Firefox supports (Windows XP and up, OSX 10.6 and up, Linux Pulse/Alsa/Jack, sndio, Android 2.3 and up, and even OS/2), and have all the features needed to implement what is needed for a web browser (Web Audio API, `<audio>` and `<video>`, WebRTC), in particular, synchronized audio input/output, low latency channels, device enumeration, etc.

**Comment by andrewrk** [comment]
Thanks for the info. Sounds like it's going to be a high quality project.
