### ISSUE TITLE
Move to a CMake-based build system

### ISSUE THREAD

**Issue by kinetiknz** [kinetiknz/cubeb#152]
To make libcubeb easier to build/test/debug on all platforms, a CMake-based build system that's able to generate Visual Studio projects and integrate with AndroidStudio and other build-systems/IDEs easily is desirable.  This would avoid the need to install mingw to build on Windows, and allow easier integration with things like the AndroidStudio test project in https://github.com/kinetiknz/cubeb/pull/114.

**Comment by kinetiknz** [comment]
Progress so far is in https://github.com/kinetiknz/cubeb/tree/cmake

**Comment by kinetiknz** [comment]
Green on Travis now, running the same set of builds/tests as the autotools platform.  I tried enabling the macOS tests, but they're failing due to what looks like a lack of audio hardware in the VM.

**Comment by padenot** [comment]
So cool. Want me to have a look just to make sure?

Also, yeah, we don't run the tests on OSX for now, but I have a plan, but I'm not sure it will work.

**Comment by kinetiknz** [comment]
Yeah, a second set of eyes would be awesome, thanks.

**Comment by padenot** [comment]
Building on Linux and Windows with Visual Studio Community 2015 worked fine. For windows, I tested with the CMake GUI and the command line, both worked well.

I tried a build with msys2, and there was a link error, we need to link to ole32 and oleaut32 it seems. I don't know whether we care, but it's an easy fix.

Once we decide which compiler we want to support, we can update the build docs.

**Comment by kinetiknz** [comment]
Cool, thanks for testing!

The autotools build linked ole32, but I removed that from the CMake build because it didn't seem to be needed with the VS2015 projects.

I just tried a fresh install of the non-MSYS2 mingw64 (rubenvb variant), and "mkdir build; cd build; cmake -G "MinGW Makefiles ..; mingw32-make" works with the current CMakeLists.txt in both static and dynamic mode.  That seems good enough, I'm not too worried about supporting MSYS2 or too many build system variants on Windows - a working VS2015 and a working mingw64 is probably sufficient for most uses.

**Comment by padenot** [comment]
Agreed. Once we settle on something, updating the build docs would be great.

**Comment by padenot** [comment]
@kinetiknz, do you think we could merge what you have now, or do we still have things that don't work ?

**Comment by kinetiknz** [comment]
I think it's mostly done.  I'll give the changes a once-over when I get a chance and merge if I don't spot anything requiring major changes.

**Comment by kinetiknz** [comment]
Updated the build docs, fixed some breakage from the logging changes.

**Comment by kinetiknz** [comment]
And merged in 0aea9e0438cabfe6703d587547c3a74e11380489.
