### ISSUE TITLE
Rework logging to allow plugging external logging systems

### ISSUE THREAD

**Issue by padenot** [kinetiknz/cubeb#159]
It's not rare to have to enable logging in a Firefox build, and to need logging from inside cubeb. Currently, this is not great, we need to make another build, and send it to the person, and hope to get results.

I propose the following:
- Add a new API on the cubeb context:
```c

/** Level (verbosity) of logging for a particular cubeb context. */
enum {
  CUBEB_LOG_DISABLED = 0, /** < Logging disabled */
  CUBEB_LOG_NORMAL = 1, /**< Logging lifetime operation (creation/destruction). */
  CUBEB_LOG_VERBOSE = 1 << 1, /**< Verbose logging of callbacks, can have performance implications. */
} cubeb_device_fmt;

/**
 * User supplied callback called when a message needs logging.
 * @param context A pointer to the cubeb context.
 * @param msg A c-string that contains the message to log. */
typedef void (*cubeb_logging_callback)(cubeb * context, const char * msg);

/** Set a callback to be called with a message.
    @param ctx cubeb context with witch this callback is associated
    @param level CUBEB_LOG_VERBOSE, CUBEB_LOG_NORMAL, OR-able
    @param logging_callback A function called with a message when there is something to log. Passing stdout or stderr log to this fd instead. Passing NULL allows unregistering a function.
    @retval CUBEB_OK in case of success.
    @retval CUBEB_ERROR_INVALID_PARAMETER if either ctx or
            device_changed_callback are invalid pointers, or if level is not CUBEB_LOG_VERBOSE or CUBEB_LOG_NORMAL. */
int cubeb_set_logging_callback(cubeb * ctx, int level, cubeb_logging_callback logging_callback);
```

- When the function pointer is not null, enable logging internally, either at a VERBOSE level (including callback logging), or just NORMAL (audio stream setup, error cases, etc.)
- Harmonize logging for all backends to go through this infrastructure.

If we are clever, logging won't be a perf issue. In particular, I don't think we want to lock. The idea here is to enable logging before any streams is running, so that we can avoid locking on the memory that holds the log level and pointer.

Also we need to spec the invariants for the callback function, which basically boils down to "don't call a cubeb API, directly or indirectly". 

@kinetiknz, @achronop, thoughts ?

**Comment by kinetiknz** [comment]
This would be great, and the proposal looks good.
