### ISSUE TITLE
CMake build creates additional directory dependancy 

### ISSUE THREAD

**Issue by achronop** [kinetiknz/cubeb#165]
I try to build my stand alone test and I get the following error:
```
In file included from cubeb_test.cpp:4:
../include/cubeb/cubeb.h:11:10: fatal error: 'cubeb_export.h' file not found
#include "cubeb_export.h"
````

When add the `cubeb/cubeb-build/exports` build is successful.

If the change is intentional you can ignore and close the issue.

**Comment by kinetiknz** [comment]
It's intentional and required for correct DSO generation, but I'm not super happy about it.  I couldn't find a nicer way to deal with it, but I may revert to a bunch of #defines at the top of cubeb.h instead.
