### ISSUE TITLE
install.md may need to be updated

### ISSUE THREAD

**Issue by ChunMinChang** [kinetiknz/cubeb#199]
Without the `git submodule update --init --recursive` command, no VC++ Project file will be produced.

1. `git clone https://github.com/kinetiknz/cubeb.git`
2. `mkdir cubeb-build`
3. `cd cubeb && git submodule update --init --recursive`
3. `cd ../cubeb-build`
3. `cmake ../cubeb`
4. `cmake --build .`
5. `ctest`

**Comment by kinetiknz** [comment]
Thanks for pointing that out!
