### ISSUE TITLE
Fix -Wformat issues in the tree introduced by LOG()

### ISSUE THREAD

**Issue by kinetiknz** [kinetiknz/cubeb#203]
@tromey is trying to add -Wformat to the Gecko build, but there are a bunch of warnings produced by libcubeb.  See https://treeherder.mozilla.org/logviewer.html#?job_id=33131814&repo=try#L47515

I fixed the WASAPI ones in 7073670f1621a11cf999e833a2e2309f0b98e16d and b583da9ec1f90038e90981db55d3a32518d640b3, but we need to do a fix pass over the other backends.

**Comment by tromey** [comment]
`-Wformat=error` is being done in https://bugzilla.mozilla.org/show_bug.cgi?id=1060419.  I'll probably temporarily add `-Wno-format` there, and file a followup bug to remove this after the next libcubeb import.  If there's a bug for the next libcubeb import, feel free to CC me on it.

**Comment by kinetiknz** [comment]
The `OSStatus` warnings only show up in 32-bit OS X builds.  64-bit builds are silent.  That's because we're trying to log via `%d` but `OSStatus` is a typedef of `SInt32`, which is a typedef of `signed int` on `__LP64__` and `signed long` elsewhere.

**Comment by kinetiknz** [comment]
4f0c5bd5c06dd14931ffeb1f9e11c5f5124d3231 fixes the `cubeb_audiounit.c` warnings.

**Comment by kinetiknz** [comment]
I think that's all: 32- and 64-bit Linux are -Wformat clean, we're using a different logging mechanism on Android (`__android_log_print`) for now, and Windows/MSVC needs a different annotation (`_Printf_format_string_`) which hasn't been implemented for libcubeb's logging yet.

https://bugzilla.mozilla.org/show_bug.cgi?id=1324987 tracks updating Gecko's copy of libcubeb.
