### ISSUE TITLE
pthread_cond_destroy() on uninitialized cond var in cubeb_alsa.c

### ISSUE THREAD

**Issue by MartinHusemann** [kinetiknz/cubeb#226]
alsa_stream_destroy() unconditionally frees the cond var stm->cond.
However, alsa_stream_init_single() does not initialize this before calling alsa_stream_destroy() in the error case when failing with CUBEB_ERROR_INVALID_FORMAT.

Either add a flag to note it has been initialized, or move the pthread_cond_init() up a few lines.

**Comment by kinetiknz** [comment]
Thanks for reporting this!
