### ISSUE TITLE
Error compiling on Android: static declaration of '__system_property_get' follows non-static declaration

### ISSUE THREAD

**Issue by ligfx** [kinetiknz/cubeb#278]
```
/usr/local/share/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android --gcc-toolchain=/usr/local/share/android-sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 --sysroot=/usr/local/share/android-sdk/ndk-bundle/platforms/android-21/arch-arm64 -DEXPORT="" -DFLOATING_POINT -DGTEST_HAS_TR1_TUPLE=0 -DOUTSIDE_SPEEX -DRANDOM_PREFIX=speex -DUSE_AUDIOTRACK -DUSE_OPENSL -I../include -I../src -Iexports -isystem /usr/local/share/android-sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include -funwind-tables -no-canonical-prefixes -fexceptions -Wall -Wextra -Wno-unused-parameter -g -fPIC -fvisibility=hidden   -std=gnu99 -MD -MT CMakeFiles/cubeb.dir/src/cubeb_opensl.c.o -MF CMakeFiles/cubeb.dir/src/cubeb_opensl.c.o.d -o CMakeFiles/cubeb.dir/src/cubeb_opensl.c.o   -c ../src/cubeb_opensl.c
../src/cubeb_opensl.c:626:1: error: static declaration of '__system_property_get' follows non-static declaration
__system_property_get(const char* name, char* value)
^
/usr/local/share/android-sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include/sys/system_properties.h:47:5: note: previous declaration is here
int __system_property_get(const char *name, char *value);
    ^
1 error generated.
```

The internet says that `__system_property_get` was being removed from the NDK headers, but it's available for pretty much every architecture/API level on my machine (macOS, latest NDK downloaded with `sdkmanager ndk-bundle`) and is actually _recommended_ in the [Android 7.0 update document](https://developer.android.com/about/versions/nougat/android-7.0-changes.html). I'd put up a PR, but I don't know what the correct approach is here.

**Comment by kinetiknz** [comment]
I'd be happy if we could use it directly, but it's not clear to me what the current situation is.  I tried digging through the git history of the relevant Android repos, but didn't find an answer.  For Firefox integration, I think we're still on NDK 11c and API level 14, so anything that works with that is fine with me.

**Comment by kinetiknz** [comment]
@ligfx What do you think of https://github.com/kinetiknz/cubeb/commit/5e822c6bb87fb4b13728991502d135b61d5401ec as a short term fix?  That builds in various configurations for me, but I haven't tested it at runtime yet.

**Comment by ligfx** [comment]
@kinetiknz Haha yeah I'm as in the dark as you are. The renaming approach in 5e822c6 seems fine to me, the functions performed identically in my very limited testing.
