### ISSUE TITLE
Replace cubeb_device_collection interface.

### ISSUE THREAD

**Issue by djg** [kinetiknz/cubeb#286]
In discussion with @kinetiknz, he stated the extending-array-via-mallocing-header+data should be revisited at some point.

**Comment by padenot** [comment]
If/when you're doing this, there is another problem that we need to think about, is that the lifetime of the device themselves is weird, and we're doing all sorts of weird index mapping in gecko.

It would be good to have stable indexes or devices.

**Comment by djg** [comment]
@padenot I've opened Issue #298 to track the problem you've raised. I have patches to improve things.

**Comment by kinetiknz** [comment]
Fixed by #309
