### ISSUE TITLE
Improve cubeb_devid lifetime

### ISSUE THREAD

**Issue by djg** [kinetiknz/cubeb#298]
In backends that support device enumeration, a majority of them (cubeb_pulse, cubeb_alsa, cubeb_wasapi) cast a string to int to return as the value for cubeb_devid.  These strings only last for the lifetime of the enumeration API call.

It is desirable to improve cubeb_devid such that ids are:
- Have lifetime longer than the immediate scope of device enumeration call, and are
- Cheap to compare, clone and copy.

**Comment by kinetiknz** [comment]
Fixed by #299
