### ISSUE TITLE
audiounit: cubeb_mixer writes outside output array

### ISSUE THREAD

**Issue by djg** [kinetiknz/cubeb#305]
This line looks suspicious and causes test_mixer to write outside the array in 3f2 -> mono downmix.

[heap array out-of-bound write](https://github.com/kinetiknz/cubeb/blob/0c74372fd5e24d3ed0316bbb656a5f5995fc25b0/src/cubeb_mixer.cpp#L280) 

@ChunMinChang please take a look.

**Comment by ChunMinChang** [comment]
Thanks for the report. #310 should solve this!

**Comment by djg** [comment]
@ChunMinChang thanks for the explanation.

**Comment by kinetiknz** [comment]
Fixed by #310
