### ISSUE TITLE
Assert in audiounit_set_global_latency

### ISSUE THREAD

**Issue by achronop** [kinetiknz/cubeb#410]
Error found in: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5189353c6423&selectedJob=160040068

Regression from commit [1f4b4de](https://github.com/kinetiknz/cubeb/commit/1f4b4d33b1aa378ae751cfa011ba6faec2759127). Unlocking and re-locking the context mutex in `stream_destroy()` allow a new `stream_init()` to progress and advance the `active_streams` counter. In different case `stream_init` would wait [here](https://searchfox.org/mozilla-central/source/media/libcubeb/src/cubeb_audiounit.cpp#2604). 

A solution would to change the `stream_destroy()` and decrease the `active_streams` counter inside the serial queue which is protected by stream mutex.

@padenot thoughts?

**Comment by padenot** [comment]
Yeah ok, makes sense.
