### ISSUE TITLE
add explicit device selection

### ISSUE THREAD

**Issue by camlorn** [kinetiknz/cubeb#42]
I'm looking at using Cubeb for my own project, and one of the features I wish to support is explicit device selection.  If a standard API can be decided upon, I can do the work for the Windows backends, but am not yet in the position to do so for Linux, mac, and Android.  I'm seriously considering doing the work on Windows for my own project; consequently, I want to hash out what would be needed to get it upstream.

**Comment by ieei** [comment]
1y later - I've been working on an enumeration API. This could then again be used for device selection. (Which is the next thing I was thinking of doing.) See https://github.com/ieei/cubeb/commits/dev_enum

**Comment by kinetiknz** [comment]
This is in now.
