### ISSUE TITLE
Cannot Build Cubeb with Visual Studio

### ISSUE THREAD

**Issue by camlorn** [kinetiknz/cubeb#43]
I'm working on this via making CMake scripts, which can be a nice alternative to autoconf on Windows (and possibly OS X).  I'll submit a pull request when I have something that compiles; I expect few if any source changes will need to be made.  The big one seems to be that we aren't running the `ax_create_stdint_.h.m4`, which can be gotten around via macros in the header that include `stdint.h` when VC++ is detected (I am going to try to detect C99 directly, but if that fails...).
Recent versions of Visual Studio implement most parts of C99 and basically all of C++11, so I can definitely get this going on VC++ 2013.  I'm not sure how far back my changes will work due to not having older versions installed as multiple versions of VS never quite play nice in my experience.
if there are any must-nots, let me know.

**Comment by padenot** [comment]
We can now close this, the CMake backend has been merged and it works nicely with visual studio.
