### ISSUE TITLE
Fail to unregister device changed callback with audiounit_stream_register_device_changed_callback

### ISSUE THREAD

**Issue by ChunMinChang** [kinetiknz/cubeb#475]
By the following comment,
https://github.com/kinetiknz/cubeb/blob/9a7a55153e7f9b9e0036ab023909c7bc4a41688b/src/cubeb_audiounit.cpp#L3102-L3105
it should have a way to unregister the `device_changed_callback` in the `stream`.  If `audiounit_stream_register_device_changed_callback` can cancel the original callback by registering a null callback, like what `audiounit_register_device_collection_changed` does, the following code should work:
```cpp
r = cubeb_stream_register_device_changed_callback(stream, device_changed_callback);
ASSERT_EQ(r, CUBEB_OK) << "Error registering device changed callback";

r = cubeb_stream_register_device_changed_callback(stream, nullptr);
ASSERT_EQ(r, CUBEB_OK) << "Error unregistering device changed callback";
```

However, the above test code hit the assertion `assert(!stream->device_changed_callback)`. When the second `cubeb_stream_register_device_changed_callback` is called for unregistering, `stream->device_changed_callback` is not null.

If above test code is the expected behavior, I'd like to add tests for it. It can also help to verify the Rust implementation.

**Comment by achronop** [comment]
Better to allow that for symmetry with the `register_device_collection_changed` api logic. Also the assert there is not very important since we do not call any method from the framework. We can simple remove it.

**Comment by ChunMinChang** [comment]
This is fixed in the Rust version.
