### ISSUE TITLE
(Windows/winmm) Device friendly_name is capped at 31 characters

### ISSUE THREAD

**Issue by codecat** [kinetiknz/cubeb#491]
I'm printing the devices to console, and I see the following:

```
Devices:
  Rear Audio (High Definition Aud
  Front Audio (High Definition Au
```

The code used:

```c++
cubeb_device_collection collection;
cubeb_enumerate_devices(ctx, CUBEB_DEVICE_TYPE_OUTPUT, &collection);

printf("Devices:\n");
for (size_t i = 0; i < collection.count; i++) {
	auto &device = collection.device[i];
	printf("  %s\n", device.friendly_name);
}

cubeb_device_collection_destroy(ctx, &collection);
```

**Comment by kinetiknz** [comment]
Thanks for the bug report.  That's a limitation of Window's WinMM API - The szPname field of [WAVEOUTCAPS](https://docs.microsoft.com/en-us/windows/desktop/api/mmeapi/ns-mmeapi-waveoutcaps) is limited to MAXPNAMELEN (32) characters.

From a quick look around, workarounds involve enumeration via DirectSound and jumping through hoops to map DirectSound devices to WinMM devices.  cubeb's winmm backend is effectively in maintenance-only mode (it's virtually used in Firefox), so fixing this low priority for us unfortunately.  If you want to have a go at fixing this, we'd take a patch as long as it was fairly self contained.

**Comment by codecat** [comment]
Makes sense. I actually switched to WASAPI myself, which doesn't have that problem. Sidenote - why is WASAPI not the default?

**Comment by padenot** [comment]
> Sidenote - why is WASAPI not the default?

It's supposed to be picked if available. What do you observe in your program?

In any case, WASAPI is vastly superior to winmm, we're mostly keeping winmm because it's there, it works, and it doesn't really require any non trivial maintenance.

**Comment by codecat** [comment]
Initializing with `nullptr` to `backend_name` causes it to default to winmm for me. I have to manually pass `"wasapi"` to use it.

**Comment by achronop** [comment]
Have you tried it after calling `CoInitialize(nullptr)` before `cubeb_init`? As you noticed in #492, we need to call `CoInitialize(nullptr)` otherwise the `wasapi_init` method fails. When wasapi fails it resorts to `winmm` which will success since it does not have the same requirement.

**Comment by codecat** [comment]
Ah, good point! You are indeed correct, I can just pass null now and it will use wasapi.
