### ISSUE TITLE
All PulseAudio and no JACK makes cubeb a dull library

### ISSUE THREAD

**Issue by v-fox** [kinetiknz/cubeb#50]
Using JACK for Firefox now is completely dependent on upstream cubeb, in-tree one is not even updated enough to expose any JACK support. This is the most xrun-heavy piece of code on my system. And i tried playing 1080p movies with DTS sound via PA with max resampling settings as JACK client for testing under heavy load which were not giving any, in contrast to cubeb.

There are two known major issues with JACK support in cubeb:
1) Initialization order with no selection options that puts PA over JACK even if PA runs as JACK client.
Fixed [here](https://bugzilla.mozilla.org/show_bug.cgi?id=783733#c31).
2) Supposedly xruns are the result of long sleep in cubeb [here](https://github.com/kinetiknz/cubeb/blob/6de5d3e488d808dd925ae0885a7552fc0a25b449/src/cubeb_jack.cpp#L406).
I won't be surprised if there are more since that seems to be not tested at all.

**Comment by kinetiknz** [comment]
I'm happy to merge fixes to libcubeb here and review patches to fix the integration in Firefox.  Unfortunately I don't have free time to do more than that -- I'd like to see it working but I can't spend much time on it personally.

**Comment by v-fox** [comment]
I've made [packages of Firefox](https://build.opensuse.org/package/show/home:X0F:HSF/MozillaFirefox) with updated & patched cubeb. Works fine so far. Please, merge the changes and push them for upstream FF, if you can.

Initializing JACK before everything else is natural since if someone runs JACK then he really doesn't want it to latch to anything else since it would bring more load (and potential xruns) without any benefit. Especially when cubeb doesn't have any configuration/selection capabilities, that's the real problem.
Usually, cubeb really loves to give xruns for no apparent reason but with delay changed from 10000 to 1000 I haven't stumbled on one in a day. However, I'm sure there is a room for further improvement. Take a look at something like [libflashsupport-jack2](https://github.com/pvint/libflashsupport-jack2) and [freshplayerplugin](https://github.com/i-rinat/freshplayerplugin), NPAPI-flash plugin for JACK support and PPAPI-flash wrapper with JACK support, for reference.

**Comment by v-fox** [comment]
Ah, and quite a big issue is [non-existent] up/down mixing of channels for JACK. It seems on this [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=979705) that things are pretty bad for Windows® output but at least some work is happening with it. Not so much for JACK. Why is mixing code is not platform-independent even ?

**Comment by zamaudio** [comment]
Improved duplex JACK backend in #108

**Comment by kinetiknz** [comment]
Closing due to #108 thanks to @zamaudio
