### ISSUE TITLE
Deprecating cubeb_stream_register_device_changed_callback?

### ISSUE THREAD

**Issue by kinetiknz** [kinetiknz/cubeb#517]
Currently cubeb_stream_register_device_changed_callback is only implemented in the cubeb_audiounit backend.  Within Gecko, it's used to notify GraphDriver::DeviceChanged and to execute the macOS-specific PanOutputIfNeeded workaround.

If the current existing use could be serviced with a device collection callback instead (by triggering an enumeration and then checking if the cubeb_devid the stream was opened with was still marked as the default/preferred stream in the updated cubeb_device_info.

That'd require some extra code on the Gecko side, but it'd simplify the cubeb backend implementations (primarily cubeb_audiounit) and the AudioIPC remoting.

**Comment by padenot** [comment]
This one is a bit complex. Sometimes the device collection does not change, but the device being used changes. On OSX, when you unplug or plug headphones, it's the "source" on the device that changes, not the device, and this is hard to find when enumerating (the device is still the onboard audio chip, I think it's just the name of the device that changes).

This is rather critical to reset the echo cancellation, when doing calls.

I was thinking of removing the panning from the cubeb API, though. This is best done by clients.

**Comment by achronop** [comment]
Paul is right, OSX has a number of quirks. However, I understand the need to remove that callback. First, it is only implemented in audiounit backend. Second, looking at the implementation we trigger that callback in the same cases that we trigger `device_collection_change_callback` [1]. The identification of the device, if it is the internal OSX mic or not, happens on the Gecko side [2] which makes it independent of the callback. If we test carefully the new approach, I believe, we can deprecate that one, simplify the API and use one callback for every device change.

[1] https://searchfox.org/mozilla-central/rev/11712bd3ce7454923e5931fa92eaf9c01ef35a0a/media/libcubeb/src/cubeb_audiounit.cpp#968-976
[2] https://searchfox.org/mozilla-central/rev/11712bd3ce7454923e5931fa92eaf9c01ef35a0a/dom/media/GraphDriver.cpp#1046-1048

**Comment by padenot** [comment]
Ok.

**Comment by kinetiknz** [comment]
Thanks for the feedback.  I hadn't fully considered the issue where a field on the cubeb_device_info changes (i.e. the default/preferred flag) without triggering a callback.  I think the complexity of implementing that functionality in each backend outweighs keeping the current API, so I'll close this issue.

**Comment by kinetiknz** [comment]
> I was thinking of removing the panning from the cubeb API, though. This is best done by clients.

 Sounds fine to me, but probably worth opening a new issue to track that.
