### ISSUE TITLE
Any reason to not dlopen libasound?

### ISSUE THREAD

**Issue by lunixbochs** [kinetiknz/cubeb#525]
Linux environments are very diverse. Would be nice to be able to use alsa without a hard dependency on it. For now I'm disabling alsa in my builds instead.

**Comment by kinetiknz** [comment]
There's no reason, it was just not required at the time.  The ALSA backend is unmaintained now, so disabling it at build time is probably the best option.  A patch use dlopen would be accepted, though.

**Comment by lunixbochs** [comment]
Ok, thanks. I’ll probably leave it disabled unless a user needs it and is unwilling to use pulse or jack, then I’ll do the dlopen patch.

**Comment by kinetiknz** [comment]
https://github.com/kinetiknz/cubeb/pull/539 adds support for this.

**Comment by lunixbochs** [comment]
awesome, thanks for letting me know
