### ISSUE TITLE
Returned channel count is not updated when default device changes on Linux

### ISSUE THREAD

**Issue by achronop** [kinetiknz/cubeb#545]
The `cubeb_get_max_channel_count()` is not updated when the default device changes. For example, if a stereo output device is plugged in, this method will correctly return `2`. However, if the default output device is being switched to a multichannel one, let's say `8` channels, the return value is again `2` instead of `8`. The same problem also occurs on a multichannel device when the configured number of channels changes. For example, if the configuration of a multichannel device changes from `8` to `3`, the method above will still return `8`. This happens on both Pulse Audio backends (`pule` and `pulse-rs`).

**Comment by kinetiknz** [comment]
See fix in PR https://github.com/kinetiknz/cubeb/pull/547

**Comment by achronop** [comment]
Fix for the rust backend: https://github.com/djg/cubeb-pulse-rs/pull/48
