### ISSUE TITLE
Jack backend, firefox, and audio capture

### ISSUE THREAD

**Issue by perkinslr** [kinetiknz/cubeb#550]
For the past year or so, Firefox built with `--enable-jack` has not been able to add any writable ports.  After digging into it, adding a bunch of `printf`s, I have some idea what the trouble is, but don't know how best to fix it.

In cubeb_jack.cpp:cbjack_stream_init, it checks if `input_device` or `output_device` are pre-specified, and gives up if one of them is.  In cubeb's unit tests, those are NULL, so everything works as intended.  When used from firefox, `output_device` is not NULL.  

As a workaround, I just commented out the return in that check, and everything appears to work, but that cannot be the proper solution.  

I'm happy to keep digging into this, but I'd like some pointers on where I'm likely to find the actual source of the trouble.  Is Firefox the likely culprit, or is it likely something in cubeb that's initializing the device early?

**Comment by kinetiknz** [comment]
Thanks for the bug report.  The JACK backend isn't really maintained, but given your investigation into the issue I took a quick look and came up with a simple possible fix.  I haven't had a chance to test it, but if you could try it and report back that'd be great.  The change is in the issue550 branch, see here: https://github.com/kinetiknz/cubeb/commit/5dc6a4d79c29d7cf2ecd65efb4401d860140b1cb

**Comment by perkinslr** [comment]
Ah, that makes perfect sense for why this is happening.  So far that appears to have fixed the issue.  I'll be using it extensively Saturday, I'll let you know how it goes.  

As for the jack backend being unmaintained, I had not realized that or I would have dug into this sooner.  I plan to continue using it for the foreseeable future; it's simple enough that I'm pretty certain I can keep it running.  If it breaks in the future, I'll probably be back with pull requests.

**Comment by perkinslr** [comment]
Successfully used it for ~5 hours today.  It works on a bunch of different websites too.

**Comment by kinetiknz** [comment]
Thanks for confirming, I'll get the patch merged.
