### ISSUE TITLE
Wasapi loopback returns 0 frames

### ISSUE THREAD

**Issue by geekuillaume** [kinetiknz/cubeb#605]
When trying to use `CUBEB_STREAM_PREF_LOOPBACK` with Wasapi backend, data_callback is called with nframes equals to zero. Maybe related: `test_loopback` fails with:

```
PS C:\Users\Geekuillaume\code\cubeb\build\Debug> .\test_loopback.exe    
Running main() from gtest_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from cubeb
[ RUN      ] cubeb.loopback_duplex
stream started
stream stopped
stream started
stream stopped
[       OK ] cubeb.loopback_duplex (7521 ms)
[ RUN      ] cubeb.loopback_separate_streams
C:\Users\Geekuillaume\code\cubeb\test\test_loopback.cpp(192): error: Value of: (void *) 0
  Actual: NULL
Expected: outputbuffer
Which is: 012D4E98
outputbuffer should be null in input only callback
C:\Users\Geekuillaume\code\cubeb\src\cubeb_wasapi.cpp:811 - fatal error: out_frames >= 0
```

I'm testing this with Windows 10 19041.264.

**Comment by padenot** [comment]
I have lots of Windows/WASAPI fixes in flight and will do more when I get back from holidays, on the 31st, sorry about this bug.

Is this running on the CI? afaik the CI is green, but I don't know what it's running.

**Comment by geekuillaume** [comment]
No worry, enjoy your time off :) Bonne vacances !

**Comment by padenot** [comment]
I haven't been able to reproduce this on the machines I have access to.

**Comment by geekuillaume** [comment]
This bug only occurs when running with the default audio output of a Windows VM inside VirtualBox. I don't think it's something cubeb can fix. I'm closing this issue.
