### ISSUE TITLE
TravisCI no longer works

### ISSUE THREAD

**Issue by jbeich** [kinetiknz/cubeb#606]
Looking at new pull requests only AppVeyor is still run but it doesn't cover Linux, macOS, FreeBSD. For example, #600, #603 affect FreeBSD (but not Linux due to missing jack package) while #604 affects Linux/macOS/FreeBSD.

**Comment by kinetiknz** [comment]
Thanks for reporting this! Not sure what happened, but possibly related to [this issue with legacy Travis configurations](https://travis-ci.community/t/github-status-not-posted-on-commits-on-repositories-using-legacy-service-integration/7798). I recreated the Travis configuration and it is working for new pushes (and #600, which was showing up on the Travis side and is showing up on GitHub after a retrigger) but not sure how to trigger retries for #603/#604.

**Comment by spinnylights** [comment]
Should I open a new pull request from scratch for https://github.com/kinetiknz/cubeb/pull/603? I tried closing/reopening the PR but no luck re Travis.

**Comment by spinnylights** [comment]
Should I just open a new PR for https://github.com/kinetiknz/cubeb/pull/603? I tried closing/reopening it and rebasing against upstream (which needed to get done anyway at least) and Travis still isn't running. Their docs [claim it ought to work as long as there's no merge conflicts](https://docs.travis-ci.com/user/pull-requests/#my-pull-request-isnt-being-built) so I'm not sure what else I could try from my side.
