### ISSUE TITLE
WASAPI: Failure to initialize client for S16 cubeb stream when mix format is WAVE_FORMAT_IEEE_FLOAT

### ISSUE THREAD

**Issue by ggrtk** [kinetiknz/cubeb#626]
When the cubeb stream being passed to `setup_wasapi_stream_one_side()` is a `CUBEB_SAMPLE_S16NE` stream and `GetMixFormat()` returns a `WAVE_FORMAT_IEEE_FLOAT` for the format tag, cubeb submits an invalid mix format to `IAudioClient::Initialize()`. This seems to be happening because `wBitsPerSample` is set to 16 based on the cubeb stream but the format tag is kept at `WAVE_FORMAT_IEEE_FLOAT`, which is incompatible with `wBitsPerSample` values that are not 32. In this case, the format tag should probably be set to `WAVE_FORMAT_PCM` like what is being done for WinMM.

**Comment by kinetiknz** [comment]
Fixed in #628, thanks.
