### ISSUE TITLE
enumerate_devices for PulseAudio

### ISSUE THREAD

**Issue by achronop** [kinetiknz/cubeb#68]
Method enumerate_devices for PulseAudio follows the pattern of calling async methods and waiting for the results in order to continue (like the rest of the code). What stranges me here is that it does not hold the mutex before async method(s) call and it does not signal from inside the callbacks like purposed in pulse documentations.

http://freedesktop.org/software/pulseaudio/doxygen/threaded_mainloop.html#basic_subsec

To be honest I use it a lot in my examples without any problem so I wonder what I am missing here and if we will be fine since this code is landed in firefox and will be overused.

**Comment by kinetiknz** [comment]
None of the device enumeration API is used in Firefox yet, so beyond the testing Haakon did and what I noticed in the review during merge, it hasn't had a lot of scrutiny yet... so it's very possible that there are bugs.  Sounds like this needs more investigation.

**Comment by achronop** [comment]
This issue solved with #71
